[build]
  publish = "dist"
  command = "npm run generate"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[plugins]]
  package = "@netlify/plugin-local-install-core"

[[plugins]]
  package = "/netlify-plugins/algolia-export"
    [plugins.inputs]
      exclude = ['''^\/(?!blog\/[0-9]{4}\/[0-9]{2}\/[0-9]{2}\/(?!index.html)).*''']

[[plugins]]
  package = "@netlify/plugin-sitemap"

    [plugins.inputs]
    exclude = [
      './dist/404.html',
      './dist/googledd87c7542bc7fce5.html',
      './dist/admin'
    ]
    changeFreq = "daily"
    priority = 0.5

[[redirects]]
  from = "/Vonage-footer-logo.svg"
  to = "/.netlify/functions/image-svg"
  status = 200
  force = true

[[redirects]]
  from = "/onehack"
  to = "/courses/onehack"
  status = 301
  force = true

[[redirects]]
  from = "/api/live-on-twitch"
  to = "/.netlify/functions/live-on-twitch"
  status = 200
  force = true

[[redirects]]
  from = "/blog/tag/conversation-api/"
  to = "/tags/conversation-api/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/voice/"
  to = "/tags/voice-api/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/verify/"
  to = "/tags/verify-api/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/sms/"
  to = "/tags/sms-api/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/number-insight/"
  to = "/tags/number-insight-api/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/messages/"
  to = "/tags/messages-api/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/tag/dispatch/"
  to = "  /tags/dispatch-api/"
  status = 301
  force = true


